name: Fetch Facebook Posts

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '*/15 * * * *'  # Automatically runs every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests feedgen

      - name: Run script
        run: python facebook_to_rss.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Commit and push RSS feed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add facebook_feed.xml
          git commit -m "Update RSS feed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}